module.exports = {
  USER_REGISTERED: 'USER_REGISTERED',
  ORDER_CREATED: 'ORDER_CREATED',
  ORDER_ACCEPTED: 'ORDER_ACCEPTED',
  ORDER_READY: 'ORDER_READY',
  ORDER_ASSIGNED: 'ORDER_ASSIGNED',
  PAYMENT_COMPLETED: 'PAYMENT_COMPLETED',
  DELIVERY_COMPLETED: 'DELIVERY_COMPLETED',
  REVIEW_CREATED: 'REVIEW_CREATED',
  MENU_ITEM_UPDATED: 'ordermitra.menu.update'
};
